- name: Restart k3s on servers
  hosts: servers
  become: true
  gather_facts: false

  tasks:
    - name: Restart k3s
      ansible.builtin.systemd_service:
        name: k3s.service
        state: restarted

- name: Restart k3s on agents
  hosts: agents
  become: true
  gather_facts: false

  tasks:
    - name: Restart k3s-agent
      ansible.builtin.systemd_service:
        name: k3s-agent.service
        state: restarted
