- name: Uninstall open-iscsi
  hosts: nodes
  become: true
  gather_facts: false

  tasks:
    - name: Ensure iscsid is disabled and stopped
      ansible.builtin.systemd_service:
        name: iscsid.service
        enabled: false
        state: stopped
      failed_when: false
    - name: Ensure open-iscsi is not installed
      ansible.builtin.apt:
        name: open-iscsi
        state: absent
