- name: Check root privileges on hosts
  hosts: nodes

  tasks:
    - name: Try running a command
      ansible.builtin.command: echo "Hello World!"
      changed_when: false
    - name: Try running a command as root
      ansible.builtin.command: whoami
      become: true
      register: whoami_output
      changed_when: false
    - name: Assert that can become root
      ansible.builtin.assert:
        that:
          - whoami_output["stdout"] == "root"
