- name: Remove k3s_data LVM partition
  hosts: nodes
  become: true
  gather_facts: false

  tasks:
    - name: Set root volume group
      ansible.builtin.set_fact:
        volume_group: rootvg

    - name: Remove /etc/fstab entry for k3s_data
      ansible.posix.mount:
        src: "/dev/{{ volume_group }}/k3s_data"
        path: /mnt/storage
        state: absent
    - name: Remove mountpoint for k3s_data
      ansible.builtin.file:
        path: /mnt/k3s_data
        state: absent
    - name: Remove k3s_data volume
      community.general.lvol:
        vg: "{{ volume_group }}"
        lv: k3s_data
        state: absent
        force: true
