- name: Remove storage LVM partition
  hosts: nodes
  become: true
  gather_facts: false

  tasks:
    - name: Set root volume group
      ansible.builtin.set_fact:
        volume_group: rootvg

    - name: Remove /etc/fstab entry for cluster storage
      ansible.posix.mount:
        src: "/dev/{{ volume_group }}/storage"
        path: /mnt/storage
        state: absent
    - name: Remove mountpoint for cluster storage
      ansible.builtin.file:
        path: /mnt/storage
        state: absent
    - name: Remove storage volume
      community.general.lvol:
        vg: "{{ volume_group }}"
        lv: storage
        state: absent
        force: true
