- name: Set common facts for nettops
  hosts: nettops
  become: true
  gather_facts: true

  tasks:
    - name: Set common facts for nettops
      ansible.builtin.set_fact:
        volume_group: "{{ ansible_hostname | capitalize }}-vg"


- name: Set common facts for proxmox VMs
  hosts: proxmox
  become: true
  gather_facts: true

  tasks:
    - name: Set common facts for proxmox VMs
      ansible.builtin.set_fact:
        volume_group: "{{ ansible_hostname }}-vg"


- name: Setup LVM partitions for cluster
  hosts: nodes
  become: true
  gather_facts: false

  tasks:
    - name: Grow var volume
      community.general.lvol:
        vg: "{{ volume_group }}"
        lv: var
        size: 20g
        resizefs: true

    - name: Create k3s volume
      community.general.lvol:
        vg: "{{ volume_group }}"
        lv: k3s_data
        size: 20g
    - name: Create filesystem for k3s volume
      community.general.filesystem:
        fstype: ext4
        dev: "/dev/{{ volume_group }}/k3s_data"
    - name: Create mountpoint for k3s data
      ansible.builtin.file:
        path: /var/lib/rancher/k3s
        owner: root
        group: root
        mode: "755"
        state: directory
    - name: Configure /etc/fstab for k3s data
      ansible.posix.mount:
        src: "/dev/{{ volume_group }}/k3s_data"
        path: /var/lib/rancher/k3s/
        fstype: ext4
        opts: "defaults"
        state: mounted
        boot: true
    - name: Enable dm_crypt kernel module
      community.general.modprobe:
        name: dm_crypt
        persistent: present
    - name: Enable dm_thin_pool kernel module
      community.general.modprobe:
        name: dm_thin_pool
        persistent: present
