- name: Setup different packages that make life easier
  hosts: nodes
  become: false
  gather_facts: true

  tasks:
    - name: Ensure that byobu is installed
      ansible.builtin.apt:
        name: byobu
        state: present
    - name: Ensure that neovim is installed
      ansible.builtin.apt:
        name: neovim
        state: present
