- name: Ignore power button for poweroff
  hosts: nettops
  become: true
  gather_facts: false

  tasks:
    - name: Prevent power button
      ansible.builtin.lineinfile:
        path: /etc/systemd/logind.conf
        regexp: '^#HandlePowerKey=.*$'
        line: 'HandlePowerKey=ignore'
