- name: Configure users and SSH
  hosts: nodes
  become: true
  gather_facts: false

  tasks:
    - name: Set ansible user shell to bash
      ansible.builtin.shell: sudo chsh -s $(which bash) $(whoami)
      become: false
      changed_when: true
    - name: Add primary user to sudo group
      ansible.builtin.user:
        name: gmatiukhin
        groups: sudo
        append: true
    - name: Create .ssh directory for primary user
      ansible.builtin.file:
        path: /home/gmatiukhin/.ssh
        owner: gmatiukhin
        group: gmatiukhin
        state: directory
        mode: '0700'
    - name: Add SSH authorized keys
      ansible.builtin.uri:
        url: https://github.com/gmatiukhin.keys
        dest: /home/gmatiukhin/.ssh/authorized_keys
        creates: /home/gmatiukhin/.ssh/authorized_keys
        owner: gmatiukhin
        group: gmatiukhin
        mode: '0700'
    - name: Allow SSH public key authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PubkeyAuthentication yes$'
        line: 'PubkeyAuthentication yes'
    - name: Prohibit SSH password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication yes$'
        line: 'PasswordAuthentication no'
