- name: Configure users and SSH
  hosts: nodes
  become: yes
  gather_facts: no

  tasks:
  - name: Set ansible user shell to bash
    shell: sudo chsh -s $(which bash) $(whoami)
    become: no
  - name: Ensure that curl is installed
    ansible.builtin.apt:
      name: curl
      state: present
  - name: Add primary user to sudo group
    ansible.builtin.user:
      name: gmatiukhin
      groups: sudo
      append: true
  - name: Create .ssh directory for primary user
    ansible.builtin.file:
      path: /home/gmatiukhin/.ssh
      owner: gmatiukhin
      group: gmatiukhin
      state: directory
      mode: '0700'
  - name: Add SSH idenitity
    shell: 'curl https://github.com/gmatiukhin.keys > /home/gmatiukhin/.ssh/authorized_keys'
  - name: Allow SSH public key authentication
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PubkeyAuthentication yes$'
      line: 'PubkeyAuthentication yes'
  - name: Prohibit SSH password authentication
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PasswordAuthentication yes$'
      line: 'PasswordAuthentication no'
