- name: Removes Tang pin from LUKS device
  hosts: nodes
  become: yes
  gather_facts: no

  vars_prompt:
  - name: luks_password
    prompt: Please enter your LUKS password

  tasks:
  - name: Ensure that clevis is installed
    ansible.builtin.apt:
      name: clevis
      state: present
  - name: Ensure that clevis-luks is installed
    ansible.builtin.apt:
      name: clevis-luks
      state: present
  - name: Ensure that clevis-initramfs is installed
    ansible.builtin.apt:
      name: clevis-initramfs
      state: present
  - name: Check that the encrypted disk is /dev/sda5
    command: cryptsetup luksDump /dev/sda5
  - name: Unbind previous Tang binding
    shell: >-
      bash -c
      "sudo clevis luks unbind -f -d /dev/sda5 -s 1 <<< \"{{ luks_password }}\""
  - name: Remove initramfs clevis hook file
    ansible.builtin.file:
      path: /etc/initramfs-tools/hooks/preclevis
      state: absent
  - name: Remove initramfs premount clevis script file
    ansible.builtin.file:
      path: /etc/initramfs-tools/scripts/init-premount/preclevis
      state: absent
  - name: Update initramfs
    command: "update-initramfs -u -k 'all'"
