- name: Removes Tang pin from LUKS device
  hosts: nodes
  become: true
  gather_facts: false

  vars_prompt:
    - name: luks_password
      prompt: Please enter your LUKS password

  tasks:
    - name: Ensure that clevis is installed
      ansible.builtin.apt:
        name: clevis
        state: present
    - name: Ensure that clevis-luks is installed
      ansible.builtin.apt:
        name: clevis-luks
        state: present
    - name: Ensure that clevis-initramfs is installed
      ansible.builtin.apt:
        name: clevis-initramfs
        state: present
    - name: Check that the encrypted disk is /dev/sda5
      ansible.builtin.command: cryptsetup luksDump /dev/sda5
      changed_when: false
    - name: Unbind previous Tang binding
      ansible.builtin.command:
        cmd: sudo clevis luks unbind -f -d /dev/sda5 -s 1
        stdin: "{{ luks_password }}"
      register: unbind_out
      changed_when: unbind_out.rc == 0
    - name: Remove initramfs clevis hook file
      ansible.builtin.file:
        path: /etc/initramfs-tools/hooks/preclevis
        state: absent
    - name: Remove initramfs premount clevis script file
      ansible.builtin.file:
        path: /etc/initramfs-tools/scripts/init-premount/preclevis
        state: absent
    - name: Update initramfs
      ansible.builtin.command: "update-initramfs -u -k 'all'"
      changed_when: true
